//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DataAccess.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentFile
    {
        public string FileName { get; set; }
        public string FullPath { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> Length { get; set; }
        public Nullable<int> Status { get; set; }
        public string NoTicket { get; set; }
        public string CaseNumber { get; set; }
        public int Attempts { get; set; }
        public Nullable<int> Response { get; set; }
        public string TransactionId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> DateResponse { get; set; }
        public Nullable<byte> FileResponseCreated { get; set; }
        public string FullPathResponse { get; set; }
    
        public virtual StatusFile StatusFile { get; set; }
    }
}
