//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DataAccess.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataServiceEntities : DbContext
    {
        public DataServiceEntities()
            : base("name=DataServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommentFile> CommentFile { get; set; }
        public virtual DbSet<StatusFile> StatusFile { get; set; }
        public virtual DbSet<TicketFile> TicketFile { get; set; }
        public virtual DbSet<TicketAttempt> TicketAttempt { get; set; }
    }
}
