//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DataAccess.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAttempt
    {
        public string NoTicket { get; set; }
        public int NAttempt { get; set; }
        public int Response { get; set; }
        public string Message { get; set; }
        public string TransactionId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public System.DateTime DateResponse { get; set; }
        public int Id { get; set; }
        public string Type { get; set; }
        public string Code { get; set; }
    }
}
