//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DataAtm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atm
    {
        public string SerialNumber { get; set; }
        public string IbmSerial { get; set; }
        public string IbmMachineType { get; set; }
        public string IbmMachineModel { get; set; }
        public string CitiBanamexId { get; set; }
    }
}
